name: infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Install Terraform
      working-directory: terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.14.3

    - name: Terraform init
      working-directory: terraform
      run: |
        terraform init

    - name: Terraform select workspace
      working-directory: terraform
      run: | 
        terraform workspace select prod
    
    - name: Terraform plan
      working-directory: terraform
      run: |
        terraform plan
