name: infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Check out terraform files
      uses: actions/checkout@v2

    - name: Install Terraform
      run : |
        wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
        unzip terraform_0.14.3_linux_amd64.zip
        sudo mv ./terraform /usr/local/bin
        rm -rf terraform_0.14.3_linux_amd64.zip

    - name: Terraform init
      run: |
        terraform init

    - name: Terraform select workspace
      run: | 
        terraform workspace select prod
    
    - name: Terraform plan
      run: |
        terraform plan

  apply:
    environment: prod 
    needs: plan
    defaults:
      run:
        working-directory: ./terraform
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.14.3

    - name: Check out terraform files
      uses: actions/checkout@v2

    - name: Terraform init
      run: |
        terraform init

    - name: Terraform select workspace
      run: |
        terraform workspace select prod

    - name: Terraform apply
      run: |
        terraform apply --auto-approve=true